"""Add telemetry columns for Phase 6

Revision ID: 6c2b48b03a18
Revises: 940d71e4b7bf
Create Date: 2026-04-29 17:38:45.061412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2b48b03a18'
down_revision: Union[str, Sequence[str], None] = '940d71e4b7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affinity_score', sa.Float(), nullable=False, server_default='1.0'))
        batch_op.add_column(sa.Column('skip_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_display_time', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('total_display_time')
        batch_op.drop_column('skip_count')
        batch_op.drop_column('affinity_score')

    # ### end Alembic commands ###
