"""Add display playback sessions for stateful shuffle

Revision ID: 9918fa64b736
Revises: aedcf08a6f43
Create Date: 2026-04-29 18:10:30.957628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9918fa64b736'
down_revision: Union[str, Sequence[str], None] = 'aedcf08a6f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_playback_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('unplayed_artworks_json', sa.Text(), nullable=False),
    sa.Column('last_sequential_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display_playback_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_display_id'), ['display_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_playlist_id'), ['playlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_playback_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_display_id'))

    op.drop_table('display_playback_sessions')
    # ### end Alembic commands ###
