"""Add active_displays and remote_commands for multi-worker sync

Revision ID: aedcf08a6f43
Revises: 6c2b48b03a18
Create Date: 2026-04-29 18:03:40.196130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedcf08a6f43'
down_revision: Union[str, Sequence[str], None] = '6c2b48b03a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_displays',
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('display_id')
    )
    op.create_table('remote_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_display', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_commands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_commands_target_display'), ['target_display'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_commands_target_display'))
        batch_op.drop_index(batch_op.f('ix_remote_commands_id'))

    op.drop_table('remote_commands')
    op.drop_table('active_displays')
    # ### end Alembic commands ###
